# Generated by Django 5.2.8 on 2026-01-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='price',
        ),
    ]
