# Generated by Django 5.2.8 on 2026-01-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_categories', '0003_category_is_system'),
        ('dynamic_facilities', '0002_remove_facility_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='dynamic_categories.category'),
        ),
    ]
