# Generated by Django 5.2.8 on 2026-01-30 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_categories', '0003_category_is_system'),
        ('dynamic_facilities', '0003_facility_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='service',
        ),
        migrations.AlterField(
            model_name='facility',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='dynamic_categories.category'),
        ),
    ]
