# Generated by Django 5.2.8 on 2026-02-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_facilities', '0004_remove_facility_service_alter_facility_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facility',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='Duration for slots/sessions in minutes'),
        ),
        migrations.AddField(
            model_name='facility',
            name='pricing_strategy',
            field=models.CharField(choices=[('FIXED', 'Fixed Total Price'), ('PER_UNIT', 'Per Unit (Min/Hr/Day)')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='protocol_type',
            field=models.CharField(choices=[('MINUTES_BASED', 'Minutes Based (Slots)'), ('SESSION_BASED', 'Session Based (Packages)'), ('DAY_BASED', 'Day Based (Date Range)')], default='MINUTES_BASED', max_length=20),
        ),
    ]
