# Generated by Django 5.2.8 on 2026-03-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_facilities', '0005_facility_base_price_facility_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=60, help_text='Duration for slots/sessions in minutes', null=True),
        ),
    ]
