# Generated by Django 5.2.8 on 2026-01-03 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_categories', '0001_initial'),
        ('dynamic_facilities', '0002_remove_facility_price'),
        ('dynamic_pricing', '0001_initial'),
        ('dynamic_services', '0002_service_default_billing_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pricing',
            new_name='PricingRule',
        ),
    ]
