# Generated by Django 5.2.8 on 2026-01-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0002_pricingrule_delete_pricing'),
        ('dynamic_services', '0002_service_default_billing_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingrule',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='duration',
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='billing_unit',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('PER_SESSION', 'Per Session'), ('ONE_TIME', 'One Time')], default='PER_SESSION', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='currency_code',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes for PER_SESSION or HOURLY', null=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='dynamic_services.service'),
        ),
    ]
