# Generated by Django 5.2.8 on 2026-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0003_rename_price_pricingrule_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
