# Generated by Django 5.2.8 on 2026-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0004_pricingrule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='daily_capacity',
            field=models.IntegerField(blank=True, help_text='Max bookings per day for this facility', null=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='duration_value',
            field=models.IntegerField(blank=True, help_text='Default value for HOURS, SESSIONS, etc.', null=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='monthly_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='pricing_model',
            field=models.CharField(choices=[('FIXED', 'Fixed Total'), ('PER_UNIT', 'Per Unit (Min/Hr/Day)'), ('WEEKLY', 'Weekly Rate'), ('MONTHLY', 'Monthly Rate'), ('YEARLY', 'Yearly Rate')], default='PER_UNIT', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='service_duration_type',
            field=models.CharField(choices=[('MINUTES', 'Minutes (Slots)'), ('HOURS', 'Hours'), ('DAYS', 'Days (Date Range)'), ('SESSIONS', 'Sessions (Packages)'), ('DOCTOR_VISIT', 'Doctor Visit'), ('PRODUCT', 'Product (Quantity Only)'), ('SUBSCRIPTION', 'Subscription')], default='MINUTES', max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='billing_unit',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('PER_SESSION', 'Per Session'), ('ONE_TIME', 'One Time')], default='PER_SESSION', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes for MINUTES type (slots)', null=True),
        ),
    ]
