# Generated by Django 6.0.2 on 2026-02-12 08:26

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='medical_summary',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='weight_history',
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2026, 2, 12, 8, 26, 45, 256763, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='microchip_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='PetDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('VACCINATION', 'Vaccination Record'), ('MEDICAL_REPORT', 'Medical Report'), ('OTHER', 'Other')], max_length=20)),
                ('file_url', models.FileField(upload_to='pet_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pets.pet')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PetMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, help_text='List any known allergies')),
                ('medical_conditions', models.TextField(blank=True, help_text='Existing medical conditions')),
                ('vaccination_status', models.JSONField(blank=True, default=dict, help_text='Vaccination records')),
                ('neutered', models.BooleanField(default=False)),
                ('special_notes', models.TextField(blank=True, help_text='Any special care instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='pets.pet')),
            ],
        ),
    ]
