# Generated by Django 6.0.2 on 2026-02-12 10:42

import customer_service.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_petownerprofile_address_and_more'),
        ('pets', '0002_alter_pet_options_remove_pet_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petmedicalprofile',
            name='vaccination_status',
        ),
        migrations.AddField(
            model_name='pet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='size_category',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('GIANT', 'Giant')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='temperament',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='document_name',
            field=models.CharField(default='Document', max_length=100),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='uploaded_by',
            field=models.CharField(choices=[('USER', 'User'), ('PROVIDER', 'Provider')], default='USER', max_length=10),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='verified_by_provider',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petmedicalprofile',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='petmedicalprofile',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='petmedicalprofile',
            name='last_vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petmedicalprofile',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petmedicalprofile',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='petmedicalprofile',
            name='vaccination_records',
            field=models.JSONField(blank=True, default=dict, help_text='Structured vaccination records'),
        ),
        migrations.AddField(
            model_name='petmedicalprofile',
            name='vet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='petdocument',
            name='file_url',
            field=models.FileField(upload_to='pet_documents/', validators=[customer_service.validators.validate_file_type, customer_service.validators.validate_file_size]),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner', 'status'], name='pets_pet_owner_i_8c2b43_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner', 'species'], name='pets_pet_owner_i_02358e_idx'),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('microchip_id__isnull', False)), fields=('microchip_id',), name='unique_active_microchip_id'),
        ),
    ]
