# Generated by Django 6.0.2 on 2026-02-12 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_petmedicalprofile_vaccination_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petmedicalprofile',
            name='vaccination_records',
        ),
        migrations.AddField(
            model_name='pet',
            name='blood_group',
            field=models.CharField(blank=True, help_text='e.g., DEA 1.1, A, B, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='petmedicalprofile',
            name='veterinarian',
            field=models.UUIDField(blank=True, help_text='UUID of associated business provider if any', null=True),
        ),
        migrations.AlterField(
            model_name='petdocument',
            name='document_type',
            field=models.CharField(choices=[('VACCINATION', 'Vaccination Record'), ('DIAGNOSTIC_REPORT', 'Diagnostic Report'), ('MEDICAL_REPORT', 'Medical Report'), ('PRESCRIPTION', 'Prescription'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='PetMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(help_text='e.g., 5mg, 1 tablet', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice daily, Every 8 hours', max_length=100)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetVaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date_administered', models.DateField()),
                ('next_due_date', models.DateField()),
                ('administered_by', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet')),
            ],
        ),
    ]
