# Generated by Django 6.0.2 on 2026-02-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_petmedicalprofile_vaccination_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=50),
        ),
    ]
