# Generated by Django 5.2.8 on 2025-12-23 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_employees', '0001_initial'),
        ('organizations', '0001_initial'),
        ('provider_dynamic_fields', '0001_initial'),
        ('service_provider', '0019_delete_providersyncedplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeservicesubscription',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_subscriptions', to='provider_dynamic_fields.providertemplateservice'),
        ),
        migrations.AddField(
            model_name='organizationemployee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organizationprofile'),
        ),
        migrations.AddField(
            model_name='organizationemployee',
            name='verified_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='service_provider.verifieduser', to_field='auth_user_id'),
        ),
        migrations.AddField(
            model_name='employeeservicesubscription',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='org_employees.organizationemployee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='org_employees.organizationemployee'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeservicesubscription',
            unique_together={('employee', 'service')},
        ),
    ]
