# Generated by Django 5.2.8 on 2026-02-26 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationemployee',
            name='role_name',
            field=models.CharField(default='staff', max_length=50),
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capabilities', models.JSONField(default=list, help_text='List of module.action permission strings')),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='organizations.organizationprofile')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='organizationemployee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='org_employees.organizationrole'),
        ),
    ]
