# Generated by Django 5.0.14 on 2026-03-06 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('owner_snapshot', models.JSONField(blank=True, help_text='Snapshot of owner details', null=True)),
                ('address_snapshot', models.JSONField(blank=True, help_text='Snapshot of the address at time of booking', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_id', 'status'], name='bookings_bo_owner_i_0db98f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.UUIDField(help_text='UUID of the service provider')),
                ('provider_auth_id', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_employee_id', models.UUIDField(blank=True, help_text='ID of the assigned employee', null=True)),
                ('resource_id', models.UUIDField(blank=True, help_text='ID of the assigned resource/facility', null=True)),
                ('pet_id', models.UUIDField(db_index=True)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('service_id', models.UUIDField()),
                ('facility_id', models.UUIDField()),
                ('selected_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pet_snapshot', models.JSONField(blank=True, help_text='Snapshot of pet details', null=True)),
                ('owner_snapshot', models.JSONField(blank=True, help_text='Snapshot of owner details at item level', null=True)),
                ('employee_snapshot', models.JSONField(blank=True, help_text='Snapshot of employee details', null=True)),
                ('service_snapshot', models.JSONField(blank=True, help_text='Snapshot of Service/Category/Facility names', null=True)),
                ('price_snapshot', models.JSONField(blank=True, help_text='Snapshot of pricing and billing units', null=True)),
                ('addons_snapshot', models.JSONField(blank=True, default=list, help_text='List of selected add-ons')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completion_otp', models.CharField(blank=True, max_length=4, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
            ],
            options={
                'ordering': ['selected_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by', models.UUIDField(help_text='UUID of the user who performed the action')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
                ('booking_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.bookingitem')),
            ],
            options={
                'verbose_name_plural': 'Booking Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True, help_text='The clinic or provider where this visit takes place')),
                ('pet_id', models.UUIDField(db_index=True)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('idempotency_key', models.CharField(help_text='To prevent duplicate bookings on retries', max_length=255, unique=True)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['organization_id', 'status'], name='bookings_vi_organiz_33b840_idx'), models.Index(fields=['idempotency_key'], name='bookings_vi_idempot_db5e08_idx')],
            },
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='visit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='bookings.visitgroup'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['assigned_employee_id', 'selected_time'], name='bookings_bo_assigne_1f3652_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['resource_id', 'selected_time'], name='bookings_bo_resourc_87715d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['pet_id', 'selected_time'], name='bookings_bo_pet_id_b2df83_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['provider_id', 'selected_time'], name='bookings_bo_provide_b937de_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['visit_group'], name='bookings_bo_visit_g_50814e_idx'),
        ),
    ]
