# Generated by Django 5.0.14 on 2026-03-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_providersubscription_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='providersubscription',
            name='external_subscription_id',
            field=models.CharField(blank=True, help_text='ID from Stripe/Razorpay', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='providersubscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='checkout_session_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='e.g. Stripe, Razorpay', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=0, help_text='Number of free trial days'),
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20),
        ),
    ]
