# Generated by Django 5.0.14 on 2026-03-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_subscriptionpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkout_session_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_gateway',
            field=models.CharField(default='STRIPE', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='providersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('provider_id',), name='unique_active_subscription_per_provider'),
        ),
    ]
