# Generated by Django 6.0 on 2025-12-30 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider_id', models.CharField(help_text='ID from Auth Service', max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DynamicFieldDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('CLINIC', 'Clinic'), ('OWNER', 'Pet Owner'), ('PET', 'Pet'), ('VISIT', 'Visit'), ('VITALS', 'Vitals'), ('DIAGNOSIS', 'Diagnosis'), ('LAB', 'Lab Test'), ('PRESCRIPTION', 'Prescription'), ('VACCINE', 'Vaccine')], max_length=50)),
                ('key', models.CharField(help_text="Machine key, e.g., 'temperature_c'", max_length=50)),
                ('label', models.CharField(help_text='UI Label', max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('TEXTAREA', 'Textarea'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('DROPDOWN', 'Dropdown'), ('MULTISELECT', 'Multi-Select'), ('FILE', 'File')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for DROPDOWN/MULTISELECT')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='veterinary.clinic')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('clinic', 'entity_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.CharField(blank=True, help_text='ID from Auth Service', max_length=255, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='veterinary.clinic')),
            ],
            options={
                'unique_together': {('clinic', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='veterinary.petowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('VITALS_RECORDED', 'Vitals Recorded'), ('DOCTOR_ASSIGNED', 'Doctor Assigned'), ('TESTS_ORDERED', 'Tests Ordered'), ('LAB_RESULTS_READY', 'Lab Results Ready'), ('PRESCRIPTION_FINALIZED', 'Prescription Finalized'), ('MEDICINES_DISPENSED', 'Medicines Dispensed'), ('FOLLOWUP_SCHEDULED', 'Followup Scheduled'), ('CLOSED', 'Closed')], default='CREATED', max_length=30)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='veterinary.clinic')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='veterinary.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DynamicFieldValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.UUIDField(help_text='ID of the related entity (Visit, Pet, or Virtual UUID)')),
                ('value', models.JSONField(help_text='Stores the actual value')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.dynamicfielddefinition')),
            ],
            options={
                'indexes': [models.Index(fields=['entity_id'], name='veterinary__entity__e7cacb_idx'), models.Index(fields=['definition'], name='veterinary__definit_ff1758_idx')],
            },
        ),
    ]
