# Generated by Django 6.0 on 2025-12-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict, help_text='Synced from Provider Service'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online')], default='OFFLINE', max_length=20),
        ),
    ]
