# Generated by Django 6.0 on 2025-12-30 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0002_clinic_capabilities_visit_visit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code e.g. VITALS_FORM', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, help_text='Null for global forms', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='veterinary.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(help_text='Key for JSON storage e.g. temperature', max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('SELECT', 'Select'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('TEXTAREA', 'Textarea')], max_length=20)),
                ('unit', models.CharField(blank=True, help_text='e.g. kg, bpm', max_length=20, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra config like select options')),
                ('form_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='veterinary.formdefinition')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form_definition', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='FieldValidation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('regex', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('form_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='veterinary.formfield')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_by', models.CharField(help_text='Auth User ID', max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('form_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='veterinary.formdefinition')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='veterinary.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
