# Generated by Django 6.0 on 2025-12-30 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0003_formdefinition_formfield_fieldvalidation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petowner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='petowner',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text="e.g. '1-0-1' or 'Once a day'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('next_reminder_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='ACTIVE', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='veterinary.pet')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='veterinary.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyDispense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispensed_by', models.CharField(help_text='Auth User ID', max_length=255)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DISPENSED', 'Dispensed'), ('PARTIAL', 'Partial')], default='DISPENSED', max_length=20)),
                ('prescription_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='veterinary.formsubmission')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='veterinary.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
