# Generated by Django 6.0 on 2025-12-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0004_petowner_address_petowner_email_petowner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='Unknown Pet', max_length=255),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
