# Generated by Django 6.0 on 2025-12-31 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0005_pet_breed_pet_name_pet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='lab_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='lab_ordered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='pharmacy_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='prescription_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='vitals_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='vitals_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CHECKED_IN', 'Checked In'), ('VITALS_RECORDED', 'Vitals Recorded'), ('LAB_ORDERED', 'Lab Ordered'), ('LAB_RESULTS_READY', 'Lab Results Ready'), ('PRESCRIPTION_FINALIZED', 'Prescription Finalized'), ('MEDICINES_DISPENSED', 'Medicines Dispensed'), ('CLOSED', 'Closed')], default='CREATED', max_length=30),
        ),
        migrations.CreateModel(
            name='VeterinaryAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('VITALS_ENTERED', 'Vitals Entered'), ('LAB_ORDERED', 'Lab Ordered'), ('LAB_RESULT_ADDED', 'Lab Result Added'), ('PRESCRIPTION_CREATED', 'Prescription Created'), ('MEDICINE_DISPENSED', 'Medicine Dispensed'), ('VISIT_CREATED', 'Visit Created')], max_length=50)),
                ('performed_by', models.CharField(help_text='Auth User ID', max_length=255)),
                ('capability_used', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='veterinary.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
