# Generated by Django 6.0 on 2026-01-02 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0006_visit_checked_in_at_visit_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinaryStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.CharField(help_text='ID from Auth Service', max_length=255, unique=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='veterinary.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
