# Generated by Django 6.0 on 2026-01-06 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0007_veterinarystaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='veterinary.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitCharge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Lab Test'), ('MEDICINE', 'Medicine'), ('VITALS', 'Vitals'), ('OTHER', 'Other')], max_length=30)),
                ('reference_id', models.UUIDField(blank=True, help_text='ID of lab_id / prescription_id / etc.', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='veterinary.visitinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
