# Generated by Django 6.0 on 2026-01-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0008_visitinvoice_visitcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaryauditlog',
            name='action_type',
            field=models.CharField(choices=[('VISIT_CREATED', 'Visit Created'), ('STATUS_CHANGE', 'Status Change'), ('VITALS_ENTERED', 'Vitals Entered'), ('LAB_ORDERED', 'Lab Ordered'), ('LAB_RESULT_ADDED', 'Lab Result Added'), ('PRESCRIPTION_CREATED', 'Prescription Created'), ('MEDICINE_DISPENSED', 'Medicine Dispensed'), ('INVOICE_PAID', 'Invoice Paid'), ('MEDICAL_RECORD_VIEWED', 'Medical Record Viewed')], max_length=50),
        ),
    ]
