# Generated by Django 6.0 on 2026-01-07 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0009_alter_veterinaryauditlog_action_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='provider_id',
            new_name='organization_id',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='organization_id',
            field=models.CharField(db_column='provider_id', db_index=True, help_text='ID from Auth Service (Organization Owner ID)', max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StaffClinicAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='veterinary.clinic')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_assignments', to='veterinary.veterinarystaff')),
            ],
            options={
                'unique_together': {('staff', 'clinic')},
            },
        ),
    ]
