# Generated by Django 6.0 on 2026-01-09 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0010_remove_clinic_provider_id_clinic_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='veterinarystaff',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use StaffClinicAssignment for multi-clinic support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='veterinary.clinic'),
        ),
    ]
