# Generated by Django 6.0 on 2026-01-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0011_clinic_address_clinic_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, help_text='Male, Female, etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
