# Generated by Django 6.0 on 2026-01-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0012_pet_color_pet_dob_pet_sex_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
