# Generated by Django 6.0 on 2026-01-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0013_pet_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
