# Generated by Django 6.0 on 2026-01-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0014_pet_notes_pet_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for the visit / Chief Complaint', null=True),
        ),
    ]
