# Generated by Django 6.0 on 2026-01-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0015_visit_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CHECKED_IN', 'Checked In'), ('VITALS_RECORDED', 'Vitals Recorded'), ('DOCTOR_ASSIGNED', 'Doctor Assigned'), ('LAB_REQUESTED', 'Lab Requested'), ('LAB_COMPLETED', 'Lab Completed'), ('PRESCRIPTION_FINALIZED', 'Prescription Finalized'), ('MEDICINES_DISPENSED', 'Medicines Dispensed'), ('TREATMENT_COMPLETED', 'Treatment Completed'), ('CLOSED', 'Closed')], default='CREATED', max_length=30),
        ),
    ]
