# Generated by Django 6.0 on 2026-01-13 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0016_alter_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. CBC, LFT', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('LAB_REQUESTED', 'Requested'), ('IN_PROGRESS', 'In Progress'), ('LAB_COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='LAB_REQUESTED', max_length=30)),
                ('requested_by', models.CharField(blank=True, help_text='Doctor Auth ID', max_length=255, null=True)),
                ('performed_by', models.CharField(blank=True, help_text='Lab Tech Auth ID', max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='veterinary.visit')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='veterinary.labtesttemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabTestField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='e.g. Hemoglobin', max_length=255)),
                ('unit', models.CharField(blank=True, help_text='e.g. g/dL', max_length=50, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='veterinary.labtesttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(help_text='Measured Value', max_length=255)),
                ('flag', models.CharField(blank=True, help_text='LOW, HIGH, NORMAL (Calculated)', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='veterinary.laborder')),
                ('test_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.labtestfield')),
            ],
            options={
                'unique_together': {('lab_order', 'test_field')},
            },
        ),
    ]
