# Generated by Django 5.2.8 on 2026-02-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0017_labtesttemplate_laborder_labtestfield_labresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='service_id',
            field=models.CharField(blank=True, help_text='ID of the service (Grooming, Veterinary, etc.)', max_length=255, null=True),
        ),
    ]
