# Generated by Django 5.2.8 on 2026-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0018_visit_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='created_by',
            field=models.CharField(blank=True, help_text='Auth User ID of staff who registered this pet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='petowner',
            name='created_by',
            field=models.CharField(blank=True, help_text='Auth User ID of staff who registered this owner', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='created_by',
            field=models.CharField(blank=True, help_text='Auth User ID of staff who created this visit', max_length=255, null=True),
        ),
    ]
