# Generated by Django 6.0 on 2026-02-21 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0019_pet_created_by_petowner_created_by_visit_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.UUIDField(help_text='Reference to ProviderTemplateFacility in service_provider service')),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=20)),
                ('created_by', models.CharField(choices=[('ONLINE', 'Online'), ('RECEPTIONIST', 'Receptionist')], default='ONLINE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='veterinary.clinic')),
                ('doctor', models.ForeignKey(help_text='The specific doctor assigned to this appointment', on_delete=django.db.models.deletion.PROTECT, related_name='medical_appointments', to='veterinary.staffclinicassignment')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='veterinary.pet')),
            ],
            options={
                'verbose_name': 'Medical Appointment',
                'verbose_name_plural': 'Medical Appointments',
                'ordering': ['appointment_date', 'start_time'],
            },
        ),
    ]
