# Generated by Django 6.0 on 2026-02-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0020_medicalappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointment',
            name='consultation_type',
            field=models.CharField(blank=True, help_text='Consultation type chosen by pet owner (e.g. General Checkup, Emergency)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalappointment',
            name='online_booking_id',
            field=models.UUIDField(blank=True, help_text='Links back to Booking.id in customer_service when created from online booking', null=True),
        ),
        migrations.AddField(
            model_name='medicalappointment',
            name='pet_owner_auth_id',
            field=models.CharField(blank=True, help_text='Auth user ID of the pet owner who made the online booking', max_length=255, null=True),
        ),
    ]
