# Generated by Django 6.0 on 2026-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0021_medical_appointment_online_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID from customer_service for cross-service lookup', max_length=255, null=True),
        ),
    ]
