# Generated by Django 6.0 on 2026-02-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0022_pet_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for this consultation (snapshotted at time of appointment)', max_digits=12),
        ),
    ]
