# Generated by Django 6.0 on 2026-02-23 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0023_medicalappointment_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='veterinary.medicalappointment'),
        ),
    ]
