# Generated by Django 6.0 on 2026-02-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0025_labtest_medicine_pharmacytransaction_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
