# Generated by Django 6.0 on 2026-02-23 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0026_laborder_price_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Lab Test'), ('MEDICINE', 'Medicine'), ('PROCEDURE', 'Procedure'), ('OTHER', 'Other')], max_length=30)),
                ('reference_id', models.UUIDField(blank=True, help_text='ID of lab_order / pharmacy_txn / etc.', null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='veterinary.visitinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='VisitCharge',
        ),
    ]
