# Generated by Django 6.0 on 2026-02-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0027_invoicelineitem_delete_visitcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointment',
            name='consultation_type_id',
            field=models.UUIDField(blank=True, help_text='Original ConsultationType UUID from service_provider_service', null=True),
        ),
        migrations.AddField(
            model_name='staffclinicassignment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='staffclinicassignment',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='visitinvoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='visitinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
