# Generated by Django 5.2.8 on 2026-02-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0028_medicalappointment_consultation_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarystaff',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
