# Generated by Django 6.0 on 2026-02-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0029_veterinarystaff_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointment',
            name='service_id',
            field=models.CharField(blank=True, help_text='Reference to ProviderTemplateFacility in service_provider service', max_length=255, null=True),
        ),
    ]
