# Generated by Django 6.0 on 2026-02-26 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0030_alter_medicalappointment_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetVaccinationRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dose_number', models.PositiveIntegerField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('doctor', models.CharField(blank=True, help_text='Auth ID of administering doctor', max_length=255, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='veterinary.clinic')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='veterinary.pet')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccines', to='veterinary.visit')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationReminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_date', models.DateField()),
                ('reminder_type', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='SMS', max_length=20)),
                ('sent_status', models.BooleanField(default=False)),
                ('vaccination_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='veterinary.petvaccinationrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineMaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('species', models.CharField(help_text='e.g. Dog, Cat, Bird', max_length=100)),
                ('default_interval_days', models.PositiveIntegerField(help_text='Days until next dose')),
                ('required_doses', models.PositiveIntegerField(default=1)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='veterinary.clinic')),
            ],
            options={
                'verbose_name': 'Vaccine Master',
                'verbose_name_plural': 'Vaccine Masters',
                'unique_together': {('clinic', 'vaccine_name', 'species')},
            },
        ),
        migrations.AddField(
            model_name='petvaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='veterinary.vaccinemaster'),
        ),
        migrations.AddIndex(
            model_name='petvaccinationrecord',
            index=models.Index(fields=['pet', 'vaccine'], name='veterinary__pet_id_55eb55_idx'),
        ),
        migrations.AddIndex(
            model_name='petvaccinationrecord',
            index=models.Index(fields=['next_due_date', 'status'], name='veterinary__next_du_2034fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='petvaccinationrecord',
            unique_together={('pet', 'vaccine', 'dose_number')},
        ),
    ]
