# Generated by Django 6.0 on 2026-02-28 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0031_petvaccinationrecord_vaccinationreminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='priority',
            field=models.CharField(choices=[('P1', 'Critical (P1)'), ('P2', 'Urgent (P2)'), ('P3', 'Routine (P3)')], default='P3', max_length=5),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PreVisitForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(default='1ce8278d5be94a2d9ebbdac55c7abc26', max_length=64, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_visit_form', to='veterinary.visit')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Owner'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVOICED', 'Converted to Invoice')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(help_text='Doctor auth ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='veterinary.visit')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Laboratory'), ('MEDICINE', 'Pharmacy/Medicine'), ('SURGERY', 'Surgery'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='veterinary.treatmentestimate')),
            ],
        ),
    ]
