# Generated by Django 6.0 on 2026-03-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0032_visit_priority_visit_triage_notes_previsitform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointment',
            name='consultation_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('CLINIC', 'Clinic')], default='CLINIC', max_length=15),
        ),
        migrations.AddField(
            model_name='medicalappointment',
            name='meeting_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='staffclinicassignment',
            name='is_online_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('NO_SHOW', 'No Show'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='c5e06c840bff4eb59c441fc1bb6d9ac0', max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='medicalappointment',
            index=models.Index(fields=['clinic', 'appointment_date', 'status'], name='veterinary__clinic__1c317f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalappointment',
            index=models.Index(fields=['doctor', 'appointment_date', 'status'], name='veterinary__doctor__9c9ba7_idx'),
        ),
    ]
