# Generated by Django 6.0 on 2026-03-10 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0033_medicalappointment_consultation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='b07a9850144547cbaed85fad15df5633', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pet_owner_auth_id', models.CharField(help_text='Auth User ID of the pet owner', max_length=255)),
                ('doctor_auth_id', models.CharField(blank=True, help_text='Auth User ID of the doctor', max_length=255, null=True)),
                ('created_by_auth_id', models.CharField(blank=True, help_text='Auth User ID of the creator', max_length=255, null=True)),
                ('dosage', models.CharField(max_length=100)),
                ('food_instruction', models.CharField(choices=[('BEFORE_FOOD', 'Before Food'), ('AFTER_FOOD', 'After Food'), ('WITH_FOOD', 'With Food')], max_length=20)),
                ('reminder_times', models.JSONField(help_text='List of reminder times in HH:MM format')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='veterinary.medicine')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_reminders', to='veterinary.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineReminderSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TAKEN', 'Taken'), ('MISSED', 'Missed')], default='PENDING', max_length=20)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='veterinary.medicinereminder')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.DeleteModel(
            name='MedicationReminder',
        ),
    ]
