# Generated by Django 6.0 on 2026-03-11 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0034_medicine_description_medicine_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='assigned_doctor_auth_id',
            field=models.CharField(blank=True, help_text='Auth ID of the assigned doctor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='queue_entered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visitinvoice',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='visitinvoice',
            name='lab_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='visitinvoice',
            name='medicine_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='visitinvoice',
            name='other_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='visitinvoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='67db48b6cdd44e66995c4349de42cc7e', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CHECKED_IN', 'Checked In'), ('VITALS_RECORDED', 'Vitals Recorded'), ('DOCTOR_ASSIGNED', 'Doctor Assigned'), ('CONSULTATION_DONE', 'Consultation Done'), ('LAB_REQUESTED', 'Lab Requested'), ('LAB_COMPLETED', 'Lab Completed'), ('PRESCRIPTION_FINALIZED', 'Prescription Finalized'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('MEDICINES_DISPENSED', 'Medicines Dispensed'), ('TREATMENT_COMPLETED', 'Treatment Completed'), ('CLOSED', 'Closed')], default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='visitinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='VisitStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('changed_by_user_id', models.CharField(help_text='Auth User ID of who changed it', max_length=255)),
                ('changed_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='veterinary.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
