# Generated by Django 6.0 on 2026-03-11 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0035_visit_assigned_doctor_auth_id_visit_queue_entered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='bb3d191c63c840b3a6163e6b7d1699cb', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Deworming',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField()),
                ('doctor_id', models.CharField(blank=True, help_text='Auth ID of administering doctor', max_length=255, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_deworming_records', to='veterinary.pet')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_deworming_given', to='veterinary.visit')),
            ],
            options={
                'db_table': 'deworming_records',
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='SystemDewormingReminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pet_owner_id', models.CharField(help_text='Auth ID of pet owner', max_length=255)),
                ('medicine_name', models.CharField(max_length=255)),
                ('next_due_date', models.DateField()),
                ('reminder_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent')], default='PENDING', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_deworming_reminders', to='veterinary.pet')),
            ],
            options={
                'db_table': 'deworming_reminders',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemVaccinationReminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pet_owner_id', models.CharField(help_text='Auth ID of pet owner', max_length=255)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('next_due_date', models.DateField()),
                ('reminder_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent')], default='PENDING', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_vaccination_reminders', to='veterinary.pet')),
            ],
            options={
                'db_table': 'vaccination_reminders',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField()),
                ('doctor_id', models.CharField(blank=True, help_text='Auth ID of administering doctor', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_vaccinations', to='veterinary.pet')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_vaccinations_given', to='veterinary.visit')),
            ],
            options={
                'db_table': 'vaccinations',
                'ordering': ['-date_given'],
            },
        ),
    ]
