# Generated by Django 6.0 on 2026-03-11 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0037_timestampedmodel_deworming_clinic_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_plan',
            field=models.CharField(default='BASIC', help_text='Current plan (BASIC, PRO, ENTERPRISE)', max_length=100),
        ),
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='cbb6bd5b9d3240f091f1f9803558809f', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='ClinicSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.UUIDField(db_index=True)),
                ('plan_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TRIAL', 'Trial')], default='TRIAL', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_record', to='veterinary.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
