# Generated by Django 6.0 on 2026-03-18 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0039_clinicsettings_vitals_delete_timestampedmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deworming',
            old_name='clinic_id',
            new_name='partition_clinic_id',
        ),
        migrations.RenameField(
            model_name='medicinereminder',
            old_name='clinic_id',
            new_name='partition_clinic_id',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='clinic_id',
            new_name='partition_clinic_id',
        ),
        migrations.RenameField(
            model_name='pharmacytransaction',
            old_name='clinic_id',
            new_name='partition_clinic_id',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='clinic_id',
            new_name='partition_clinic_id',
        ),
        migrations.RenameField(
            model_name='systemdewormingreminder',
            old_name='clinic_id',
            new_name='partition_clinic_id',
        ),
        migrations.RenameField(
            model_name='systemvaccinationreminder',
            old_name='clinic_id',
            new_name='partition_clinic_id',
        ),
        migrations.RenameField(
            model_name='vaccination',
            old_name='clinic_id',
            new_name='partition_clinic_id',
        ),
        migrations.RenameField(
            model_name='visitinvoice',
            old_name='clinic_id',
            new_name='partition_clinic_id',
        ),
        migrations.AddField(
            model_name='visit',
            name='consultation_notes',
            field=models.TextField(blank=True, help_text='SOAP notes / Clinical findings', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='partition_clinic_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='consultation_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='89b3af7d42ad437a95758e47d4dce17e', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CHECKED_IN', 'Checked In'), ('VITALS_RECORDED', 'Vitals Recorded'), ('CONSULTATION_IN_PROGRESS', 'Consultation In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('DOCTOR_ASSIGNED', 'Doctor Assigned'), ('LAB_REQUESTED', 'Lab Requested'), ('LAB_COMPLETED', 'Lab Completed'), ('PRESCRIPTION_FINALIZED', 'Prescription Finalized')], default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='respiration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_record', to='veterinary.visit'),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text="e.g. '1-0-1' or 'Once a day'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('next_reminder_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='ACTIVE', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='veterinary.pet')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='veterinary.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
