# Generated by Django 6.0 on 2026-03-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0040_rename_clinic_id_deworming_partition_clinic_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='13063c4e12024917aa199f60d3b62af2', max_length=64, unique=True),
        ),
    ]
