# Generated by Django 6.0 on 2026-03-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0041_pet_profile_image_alter_previsitform_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='profile_image',
            field=models.TextField(blank=True, help_text='Base64 encoded image or URL', null=True),
        ),
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='8d385775c32047c1b0bace558b4fd054', max_length=64, unique=True),
        ),
    ]
