# Generated by Django 6.0 on 2026-03-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0042_alter_pet_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='ed6877b84db24ffeb3c481f36d28fa00', max_length=64, unique=True),
        ),
    ]
