# Generated by Django 6.0 on 2026-03-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0043_alter_previsitform_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='462949a375de475592bd8f5a44e86808', max_length=64, unique=True),
        ),
    ]
