# Generated by Django 6.0 on 2026-03-23 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0044_add_medication_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='3bf794e0cbff4408bc29a22e546240fa', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pet_name', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(blank=True, max_length=50)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STOCK_CHECKED', 'Stock Checked'), ('PARTIAL_APPROVED', 'Partial Approved'), ('OTP_SENT', 'OTP Sent'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacist_auth_id', models.CharField(blank=True, max_length=255, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_orders', to='veterinary.clinic')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_order', to='veterinary.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_code', models.CharField(max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verification', to='veterinary.pharmacyorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_prescribed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_dispensed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_available', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='veterinary.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='veterinary.pharmacyorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
