# Generated by Django 6.0 on 2026-03-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0046_medicine_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointment',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Full URL for the video meeting room', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='previsitform',
            name='access_token',
            field=models.CharField(default='a477567eebdb436ba7398f607a01ae04', max_length=64, unique=True),
        ),
    ]
