# Generated by Django 5.2.7 on 2025-11-04 12:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='provider_avatars/')),
                ('avatar_size', models.CharField(blank=True, max_length=100, null=True)),
                ('is_fully_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.OneToOneField(db_column='verified_user_auth_id', on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='aadhar_docs/')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='pan_cards/')),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='gst_certificates/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.ForeignKey(db_column='verified_user_auth_id', on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to='service_provider.verifieduser', to_field='auth_user_id')),
                ('service_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=150, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('is_business_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.ForeignKey(db_column='verified_user_auth_id', on_delete=django.db.models.deletion.CASCADE, related_name='business_records', to='service_provider.verifieduser', to_field='auth_user_id')),
                ('service_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manual_verification', models.BooleanField(default=False)),
                ('automated_verification', models.BooleanField(default=False)),
                ('verified_stage', models.CharField(choices=[('personal_pending', 'Personal Info Pending'), ('business_pending', 'Business Info Pending'), ('documents_pending', 'Documents Pending'), ('verified', 'Fully Verified')], default='personal_pending', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('service_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_workflow', to='service_provider.serviceprovider')),
                ('verified_user', models.ForeignKey(db_column='verified_user_auth_id', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_records', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
        ),
    ]
