# Generated by Django 5.2.7 on 2025-11-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_serviceprovider_documentverification_businessdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
