# Generated by Django 5.2.7 on 2025-11-04 14:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_businessdetails_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerificationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=150)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='provider_documents/')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_docs', to='service_provider.documentverificationcategory')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='service_provider.serviceprovider')),
                ('verified_user', models.ForeignKey(db_column='verified_user_auth_id', on_delete=django.db.models.deletion.CASCADE, related_name='provider_documents', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
        ),
        migrations.CreateModel(
            name='AutoVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_source', models.CharField(max_length=100)),
                ('response_status', models.CharField(max_length=50)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='service_provider.providerdocument')),
            ],
        ),
    ]
