# Generated by Django 5.2.7 on 2025-11-04 15:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0004_documentverificationcategory_providerdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=150)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentverificationcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documentverificationcategory',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='documentverificationcategory',
            name='is_mandatory',
        ),
        migrations.AddField(
            model_name='documentverificationcategory',
            name='documents',
            field=models.ManyToManyField(related_name='service_types', to='service_provider.document'),
        ),
    ]
