# Generated by Django 5.2.7 on 2025-11-26 07:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0005_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalProviderPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(db_index=True)),
                ('purchase_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('plan_id', models.UUIDField(blank=True, null=True)),
                ('service_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['auth_user_id', 'service_id', 'category_id'], name='service_pro_auth_us_cab487_idx'), models.Index(fields=['auth_user_id', 'purchase_id'], name='service_pro_auth_us_dda4d4_idx')],
            },
        ),
    ]
