# Generated by Django 5.2.7 on 2025-11-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0006_localproviderpermission'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='localproviderpermission',
            name='service_pro_auth_us_cab487_idx',
        ),
        migrations.RemoveIndex(
            model_name='localproviderpermission',
            name='service_pro_auth_us_dda4d4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='localproviderpermission',
            unique_together={('auth_user_id', 'service_id', 'category_id')},
        ),
        migrations.AlterField(
            model_name='localproviderpermission',
            name='category_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localproviderpermission',
            name='service_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='localproviderpermission',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='localproviderpermission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='localproviderpermission',
            name='plan_id',
        ),
        migrations.RemoveField(
            model_name='localproviderpermission',
            name='purchase_id',
        ),
        migrations.RemoveField(
            model_name='localproviderpermission',
            name='service_name',
        ),
    ]
