# Generated by Django 5.2.7 on 2025-11-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0007_remove_localproviderpermission_service_pro_auth_us_cab487_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalProviderPermission',
        ),
    ]
