# Generated by Django 5.2.8 on 2025-12-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0008_delete_localproviderpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='verified_user',
        ),
        migrations.RemoveField(
            model_name='documentverificationcategory',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='documentverification',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='documentverification',
            name='verified_user',
        ),
        migrations.RemoveField(
            model_name='providerdocument',
            name='category',
        ),
        migrations.RemoveField(
            model_name='providerdocument',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='providerdocument',
            name='verified_user',
        ),
        migrations.RemoveField(
            model_name='verificationworkflow',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='verificationworkflow',
            name='verified_user',
        ),
        migrations.DeleteModel(
            name='AutoVerificationLog',
        ),
        migrations.DeleteModel(
            name='BusinessDetails',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentVerification',
        ),
        migrations.DeleteModel(
            name='DocumentVerificationCategory',
        ),
        migrations.DeleteModel(
            name='ProviderDocument',
        ),
        migrations.DeleteModel(
            name='VerificationWorkflow',
        ),
    ]
