# Generated by Django 5.2.8 on 2025-12-10 12:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0009_remove_businessdetails_service_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_permissions', to='service_provider.verifieduser')),
            ],
            options={
                'unique_together': {('verified_user', 'permission_code')},
            },
        ),
    ]
