# Generated by Django 5.2.8 on 2025-12-10 12:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0010_providerpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='tabler-box', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_services', to='service_provider.verifieduser')),
            ],
            options={
                'unique_together': {('verified_user', 'service_id')},
            },
        ),
    ]
