# Generated by Django 5.2.8 on 2025-12-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0011_allowedservice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerpermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='providerpermission',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerpermission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerpermission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerpermission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerpermission',
            name='category_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerpermission',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='providerpermission',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerpermission',
            name='service_icon',
            field=models.CharField(default='tabler-box', max_length=100),
        ),
        migrations.AddField(
            model_name='providerpermission',
            name='service_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerpermission',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='providerpermission',
            name='permission_code',
        ),
    ]
