# Generated by Django 5.2.8 on 2025-12-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0012_alter_providerpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerpermission',
            unique_together={('verified_user', 'service_id', 'category_id')},
        ),
    ]
