# Generated by Django 5.2.8 on 2025-12-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0013_alter_providerpermission_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerpermission',
            name='category_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='providerpermission',
            name='service_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
