# Generated by Django 5.2.8 on 2025-12-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0015_organizationemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifieduser',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationEmployee',
        ),
    ]
