# Generated by Django 5.2.8 on 2025-12-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0016_verifieduser_organization_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifieduser',
            name='organization_id',
        ),
    ]
