# Generated by Django 5.2.8 on 2025-12-22 07:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0017_remove_verifieduser_organization_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSyncedPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_plans', to='service_provider.verifieduser')),
            ],
            options={
                'unique_together': {('verified_user', 'plan_id')},
            },
        ),
    ]
