# Generated by Django 5.2.8 on 2025-12-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0018_providersyncedplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderSyncedPlan',
        ),
    ]
