# Generated by Django 5.2.8 on 2025-12-23 11:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0019_delete_providersyncedplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended')], default='invited', max_length=20)),
                ('created_by', models.UUIDField()),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='service_provider.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
