# Generated by Django 5.2.8 on 2025-12-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0020_organizationemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationemployee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizationemployee',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationemployee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='organizationemployee',
            name='role',
            field=models.CharField(default='employee', max_length=50),
        ),
    ]
