# Generated by Django 5.2.8 on 2025-12-26 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0021_organizationemployee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.CharField(max_length=255)),
                ('billing_cycle_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='service_provider.verifieduser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
