# Generated by Django 5.2.8 on 2025-12-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0022_providersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationemployee',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='PENDING', max_length=20),
        ),
    ]
