# Generated by Django 5.2.8 on 2026-01-06 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0023_alter_organizationemployee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationemployee',
            name='permissions_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProviderRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='service_provider.serviceprovider')),
            ],
            options={
                'unique_together': {('provider', 'name')},
            },
        ),
        migrations.AddField(
            model_name='organizationemployee',
            name='provider_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='service_provider.providerrole'),
        ),
        migrations.CreateModel(
            name='ProviderRoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability_key', models.CharField(max_length=100)),
                ('provider_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='service_provider.providerrole')),
            ],
            options={
                'unique_together': {('provider_role', 'capability_key')},
            },
        ),
    ]
