# Generated by Django 5.2.8 on 2026-01-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0024_organizationemployee_permissions_json_providerrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='General', max_length=50)),
            ],
        ),
    ]
