# Generated by Django 5.2.8 on 2026-01-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0025_capability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capability',
            old_name='category',
            new_name='group',
        ),
    ]
