# Generated by Django 5.2.8 on 2026-01-24 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0026_rename_category_capability_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('api_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(default='tabler-box', max_length=100)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='service_provider.capability')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.capability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_capabilities', to='service_provider.verifieduser')),
            ],
            options={
                'unique_together': {('user', 'capability')},
            },
        ),
    ]
