# Generated by Django 5.2.8 on 2026-02-02 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0027_featuremodule_providercapability'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='service_provider.verifieduser')),
            ],
        ),
    ]
