# Generated by Django 5.2.8 on 2026-02-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0029_permissionauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifieduser',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
