# Generated by Django 6.0.2 on 2026-02-12 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0030_verifieduser_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='provider_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(help_text='0-6 (Mon-Sun)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='service_provider.organizationemployee')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(help_text='0-6 (Mon-Sun)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_availability', to='service_provider.serviceprovider')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('provider', 'day_of_week')},
            },
        ),
    ]
