# Generated by Django 5.2.8 on 2026-02-13 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0031_serviceprovider_provider_type_employeeavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProviderRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField()),
                ('service_id', models.UUIDField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='service_provider.serviceprovider')),
            ],
            options={
                'db_table': 'provider_ratings',
                'ordering': ['-created_at'],
                'unique_together': {('customer_id', 'provider', 'service_id')},
            },
        ),
    ]
