# Generated by Django 5.2.8 on 2026-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0032_serviceprovider_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrating',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='customer_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
