# Generated by Django 5.2.8 on 2026-02-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0033_providerrating_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrating',
            name='provider_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerrating',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
