# Generated by Django 5.2.8 on 2026-02-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0034_providerrating_provider_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_banners/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='banner_image_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
