# Generated by Django 5.2.8 on 2026-02-13 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0035_serviceprovider_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='provider_certs/')),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='provider_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('reschedule_policy', models.TextField(blank=True, null=True)),
                ('safety_measures', models.TextField(blank=True, null=True)),
                ('house_rules', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('specializations', models.TextField(blank=True, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='provider_profiles/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='provider_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_profile', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_service_id', models.UUIDField()),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_services', to='service_provider.serviceprovider')),
            ],
            options={
                'unique_together': {('provider', 'template_service_id')},
            },
        ),
        migrations.CreateModel(
            name='ProviderServiceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='service_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service_provider.providerservice')),
            ],
        ),
    ]
