# Generated by Django 5.2.8 on 2026-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0036_providercertification_providergallery_providerpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrating',
            name='assigned_employee_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
