# Generated by Django 5.2.8 on 2026-02-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0037_providerrating_assigned_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationemployee',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='organizationemployee',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
