# Generated by Django 5.2.8 on 2026-02-21 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0011_providertemplatefacility_default_duration_minutes'),
        ('service_provider', '0039_employeeblocktime_employeeleave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeServiceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='service_provider.organizationemployee')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='provider_dynamic_fields.providertemplatefacility')),
            ],
            options={
                'verbose_name': 'Employee Service Mapping',
                'verbose_name_plural': 'Employee Service Mappings',
                'unique_together': {('employee', 'facility')},
            },
        ),
    ]
