# Generated by Django 5.2.8 on 2026-02-21 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0040_employeeservicemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDailySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_by_auth_id', models.UUIDField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='service_provider.organizationemployee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'date', 'status'], name='service_pro_employe_ec7bcf_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
