# Generated by Django 5.2.8 on 2026-02-21 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0041_employeedailyschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'General Checkup', 'Emergency'", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Typical consultation duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_types', to='service_provider.serviceprovider')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('provider', 'name')},
            },
        ),
    ]
