# Generated by Django 5.2.8 on 2026-02-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0042_consultation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationtype',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for this consultation type', max_digits=12),
        ),
    ]
