# Generated by Django 5.2.8 on 2026-02-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0043_consultationtype_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationemployee',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Individual doctor's consultation fee", max_digits=12),
        ),
        migrations.AddField(
            model_name='organizationemployee',
            name='specialization',
            field=models.CharField(blank=True, help_text='Doctor specialization (e.g. Cardiologist, Surgeon)', max_length=255, null=True),
        ),
    ]
