# Generated by Django 5.2.8 on 2026-02-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0044_organizationemployee_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrole',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='providerrole',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
