# Generated by Django 5.2.8 on 2026-02-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0045_providerrole_consultation_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerrole',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='providerrole',
            name='specialization',
        ),
    ]
