# Generated by Django 5.2.8 on 2026-02-27 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0015_providerfacilityimage_providertemplatefacilityimage'),
        ('service_provider', '0046_remove_providerrole_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='providerrole',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('component_name', models.CharField(max_length=255)),
                ('logic_type', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='OR', max_length=10)),
                ('default_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_capabilities', models.ManyToManyField(related_name='widgets', to='service_provider.capability')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Operating Room 1', 'X-Ray Machine'", max_length=100)),
                ('resource_type', models.CharField(choices=[('ROOM', 'Room'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], default='ROOM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='service_provider.serviceprovider')),
            ],
            options={
                'unique_together': {('provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserDashboardLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layout_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to='service_provider.verifieduser')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityResourceConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_constraints', to='provider_dynamic_fields.providertemplatefacility')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_links', to='service_provider.providerresource')),
            ],
            options={
                'unique_together': {('facility', 'resource')},
            },
        ),
    ]
