# Generated by Django 5.2.8 on 2026-02-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0047_providerrole_updated_at_providerrole_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
