# Generated by Django 6.0 on 2026-03-03 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0049_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='employeeleave',
            name='service_pro_employe_539fa0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='employeeleave',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='approved_by_auth_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Null means full day leave', null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Null means full day leave', null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='employeeleave',
            unique_together={('employee', 'date', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='employeeleave',
            index=models.Index(fields=['employee', 'date', 'status'], name='service_pro_employe_fca4af_idx'),
        ),
        migrations.AddField(
            model_name='employeeworkinghours',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='service_provider.organizationemployee'),
        ),
        migrations.AddIndex(
            model_name='employeeworkinghours',
            index=models.Index(fields=['employee', 'day_of_week', 'is_active'], name='service_pro_employe_239a5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeworkinghours',
            unique_together={('employee', 'day_of_week')},
        ),
    ]
