# Generated by Django 5.2.8 on 2026-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0050_employeeworkinghours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerresource',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Number of concurrent bookings this resource can handle'),
        ),
    ]
