# Generated by Django 5.2.8 on 2026-03-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0051_add_display_name_to_template_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrolecapability',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerrolecapability',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerrolecapability',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerrolecapability',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
