# Generated by Django 5.2.8 on 2026-03-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0053_add_new_vet_capabilities'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM service_provider_providerrolecapability;"),
        migrations.AlterUniqueTogether(
            name='providerrolecapability',
            unique_together=None,
        ),
        migrations.AddField(
            model_name='providerrolecapability',
            name='permission_key',
            field=models.CharField(db_index=True, default='TEMP', max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='providerrolecapability',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='providerrolecapability',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='providerrolecapability',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='providerrolecapability',
            name='can_view',
        ),
        migrations.RemoveField(
            model_name='providerrolecapability',
            name='capability_key',
        ),
        migrations.AlterUniqueTogether(
            name='providerrolecapability',
            unique_together={('provider_role', 'permission_key')},
        ),
    ]
