# Generated by Django 5.2.8 on 2026-03-31 12:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0054_alter_providerrolecapability_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaDeadLetterQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_event_id', models.UUIDField(blank=True, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retry_count', models.IntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'kafka_dead_letter_queue',
                'ordering': ['-failed_at'],
            },
        ),
        migrations.CreateModel(
            name='KafkaProcessedEvent',
            fields=[
                ('event_id', models.UUIDField(help_text='Unique UUID from the Kafka message payload', primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=50)),
                ('error_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kafka_processed_events',
                'indexes': [models.Index(fields=['event_id', 'topic'], name='kafka_proce_event_i_959a70_idx')],
            },
        ),
    ]
