# Generated by Django 5.2.8 on 2026-04-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0055_kafkadeadletterqueue_kafkaprocessedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
