# Generated by Django 5.2.8 on 2026-04-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0056_serviceprovider_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifieduser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
