# Generated by Django 5.2.8 on 2026-04-15 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0057_verifieduser_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='featuremodule',
            name='api_pattern',
        ),
        migrations.AddField(
            model_name='featuremodule',
            name='group',
            field=models.CharField(default='General', help_text='Sidebar section heading', max_length=100),
        ),
        migrations.AddField(
            model_name='featuremodule',
            name='show_in_sidebar',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actions', models.ManyToManyField(related_name='module_permissions', to='service_provider.action')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='service_provider.featuremodule')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='service_provider.providerrole')),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
    ]
