# Generated by Django 5.2.8 on 2026-01-24 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_core', '0001_initial'),
        ('plans_coupens', '0003_billingcycleconfig_alter_plan_billing_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Technical key e.g. VETERINARY_DOCTOR', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human readable name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(default='VETERINARY', help_text='Service grouping', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Unique key for the module', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('route', models.CharField(help_text='Frontend route path or name', max_length=255)),
                ('api_pattern', models.CharField(blank=True, help_text='Regex for API matching if needed', max_length=255, null=True)),
                ('icon', models.CharField(default='tabler-box', max_length=100)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='dynamic_permissions.capability')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='dynamic_permissions.capability')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_permission_capabilities', to='plans_coupens.plan')),
            ],
            options={
                'unique_together': {('plan', 'capability')},
            },
        ),
        migrations.CreateModel(
            name='ProviderCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_permissions.capability')),
                ('user', models.ForeignKey(db_column='user_auth_id', on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_capabilities', to='admin_core.verifieduser', to_field='auth_user_id')),
            ],
            options={
                'unique_together': {('user', 'capability')},
            },
        ),
    ]
