# Generated by Django 5.2.8 on 2026-01-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans_coupens', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planprice',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='purchasedplan',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
        migrations.RemoveField(
            model_name='planprice',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='default_billing_cycle',
        ),
        migrations.RemoveField(
            model_name='planprice',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='role',
        ),
        migrations.RemoveField(
            model_name='plancapability',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='plancapability',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='plancapability',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='plancapability',
            name='can_view',
        ),
        migrations.RemoveField(
            model_name='providerplancapability',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='providerplancapability',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='providerplancapability',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='providerplancapability',
            name='can_view',
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='target_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization')], default='ORGANIZATION', max_length=20),
        ),
        migrations.AddField(
            model_name='plancapability',
            name='limits',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'max_bookings': 100}"),
        ),
        migrations.AddField(
            model_name='plancapability',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'can_create': true, 'online_consult': true}"),
        ),
        migrations.AddField(
            model_name='providerplancapability',
            name='limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='providerplancapability',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='BillingCycle',
        ),
        migrations.DeleteModel(
            name='PlanPrice',
        ),
    ]
