# Generated by Django 5.2.7 on 2025-10-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_categories', '0001_initial'),
        ('dynamic_services', '0001_initial'),
        ('plans_coupens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='planitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='dynamic_categories.category'),
        ),
        migrations.AddField(
            model_name='planitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='dynamic_services.service'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='child_service_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='planitem',
            unique_together={('plan', 'service', 'category')},
        ),
    ]
