# Generated by Django 5.2.8 on 2026-01-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans_coupens', '0002_alter_purchasedplan_billing_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. MONTHLY', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='e.g. Monthly', max_length=100)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(default='MONTHLY', help_text='Code from BillingCycleConfig', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasedplan',
            name='billing_cycle',
            field=models.CharField(default='MONTHLY', max_length=50),
        ),
    ]
