# Generated by Django 6.0 on 2026-03-11 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans_coupens', '0003_billingcycleconfig_alter_plan_billing_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('capabilities', models.JSONField(default=dict, help_text="Feature flags: {'veterinary_vitals': true, 'max_doctors': 5...}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
