# Generated by Django 5.2.8 on 2026-03-25 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans_coupens', '0004_subscriptionplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchasedplan',
            index=models.Index(fields=['start_date'], name='plans_coupe_start_d_ec72b3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedplan',
            index=models.Index(fields=['is_active'], name='plans_coupe_is_acti_9a526b_idx'),
        ),
    ]
