# Generated by Django 5.2.8 on 2026-04-17 07:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans_coupens', '0006_billingauditlog_billingsequence_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRecordSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='purchasedplan',
            name='entitlement_source',
            field=models.CharField(choices=[('BILLING', 'Billing'), ('MIGRATION', 'Migration')], default='BILLING', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasedplan',
            name='is_legacy_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LegacyEntitlementRecovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('migration_record_number', models.CharField(max_length=50, unique=True)),
                ('administered_by', models.CharField(default='SYSTEM_SYNC_RECOVERY', max_length=255)),
                ('reason', models.TextField(blank=True, default='Automatic production-safe reconciliation')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('purchased_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_recovery', to='plans_coupens.purchasedplan')),
            ],
            options={
                'verbose_name_plural': 'Legacy Entitlement Recoveries',
                'db_table': 'legacy_entitlement_recovery',
            },
        ),
    ]
