# Generated by Django 5.2.8 on 2026-04-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans_coupens', '0007_migrationrecordsequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedplan',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
