# Generated by Django 5.2.7 on 2025-10-31 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.TextField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('key', models.CharField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.TextField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='pets.pettype')),
            ],
        ),
    ]
