# Generated by Django 5.0.14 on 2025-10-23 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('user_role', models.CharField(default='superAdmin', max_length=50)),
                ('is_super_admin', models.BooleanField(default=True)),
                ('activity_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('in_active', 'In Active'), ('blocked', 'Blocked')], default='in_active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
