# Generated by Django 5.2.8 on 2026-03-24 07:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0002_verifieduser_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(default='PetLeo', max_length=100)),
                ('primary_color', models.CharField(default='#7367F0', max_length=20)),
                ('secondary_color', models.CharField(default='#CE9FFC', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicons/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Branding',
                'verbose_name_plural': 'Global Branding Settings',
                'db_table': 'global_branding',
            },
        ),
    ]
