# Generated by Django 5.2.7 on 2025-10-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0002_alter_superadmin_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='auth_user_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
