# Generated by Django 5.2.8 on 2026-03-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0003_globalbranding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalbranding',
            options={},
        ),
        migrations.AddField(
            model_name='globalbranding',
            name='hide_app_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalbranding',
            name='app_name',
            field=models.CharField(default='PetLeo', max_length=255),
        ),
        migrations.AlterField(
            model_name='globalbranding',
            name='primary_color',
            field=models.CharField(default='#7367F0', max_length=7),
        ),
        migrations.AlterField(
            model_name='globalbranding',
            name='secondary_color',
            field=models.CharField(default='#CE9FFC', max_length=7),
        ),
        migrations.AlterModelTable(
            name='globalbranding',
            table=None,
        ),
    ]
