# Generated by Django 5.2.7 on 2025-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0003_alter_superadmin_auth_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='user_role',
            field=models.CharField(default='superAdmin', max_length=50, null=True),
        ),
    ]
