# Generated by Django 5.2.7 on 2025-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0004_alter_superadmin_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superadmin',
            old_name='is_superuser',
            new_name='is_admin',
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='user_role',
            field=models.CharField(default='Admin', max_length=50, null=True),
        ),
    ]
