# Generated by Django 5.2.8 on 2026-03-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0004_alter_globalbranding_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verifieduser',
            index=models.Index(fields=['created_at'], name='verified_us_created_c61b2b_idx'),
        ),
    ]
