# Generated by Django 5.2.8 on 2026-04-17 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0005_verifieduser_verified_us_created_c61b2b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderBillingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(help_text='Legal business name for invoices', max_length=255)),
                ('billing_address', models.TextField(help_text='Full registered address')),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_state_code', models.CharField(help_text='e.g. KA, MH', max_length=10)),
                ('billing_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='admin_core.verifieduser', to_field='auth_user_id')),
            ],
        ),
    ]
