# Generated by Django 5.2.7 on 2025-10-31 08:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0005_rename_is_superuser_superadmin_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'verified_users',
                'indexes': [models.Index(fields=['auth_user_id'], name='verified_us_auth_us_daf108_idx'), models.Index(fields=['email'], name='verified_us_email_0988a8_idx'), models.Index(fields=['phone_number'], name='verified_us_phone_n_c5c32b_idx')],
            },
        ),
    ]
