# Generated by Django 5.2.8 on 2026-04-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0006_providerbillingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerbillingprofile',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerbillingprofile',
            name='source',
            field=models.CharField(choices=[('ORGANIC', 'Organic'), ('RECOVERY', 'Recovery')], default='ORGANIC', max_length=50),
        ),
    ]
