# Generated by Django 5.2.7 on 2025-11-01 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0007_permission_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='verified_user',
            field=models.OneToOneField(db_column='verified_user_auth_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='admin_core.verifieduser', to_field='auth_user_id'),
        ),
    ]
