# Generated by Django 5.2.8 on 2026-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0007_providerbillingprofile_is_incomplete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_key', models.CharField(db_index=True, max_length=100)),
                ('period_date', models.DateField(blank=True, help_text='e.g. 2026-04-17 for daily snapshots', null=True)),
                ('data_json', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'indexes': [models.Index(fields=['snapshot_key', 'period_date'], name='analytics_s_snapsho_17b992_idx')],
                'unique_together': {('snapshot_key', 'period_date', 'version')},
            },
        ),
    ]
