# Generated by Django 6.0.2 on 2026-02-19 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_remove_petownerprofile_address_and_more'),
        ('pets', '0004_remove_petmedicalprofile_vaccination_records_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='customers.petownerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.UUIDField()),
                ('service_id', models.UUIDField()),
                ('facility_id', models.UUIDField()),
                ('selected_time', models.DateTimeField(blank=True, null=True)),
                ('selected_addons', models.JSONField(blank=True, default=list, help_text='List of UUIDs for selected add-ons')),
                ('extra_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pets.pet')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
