# Generated by Django 6.0.2 on 2026-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
