# Generated by Django 6.0.2 on 2026-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_price_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='employee_id',
            field=models.UUIDField(blank=True, help_text='UUID of the selected doctor/employee', null=True),
        ),
    ]
