# Generated by Django 6.0.2 on 2026-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='employee_id',
            field=models.CharField(blank=True, help_text='ID of the selected doctor/employee', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='facility_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='service_id',
            field=models.CharField(max_length=255),
        ),
    ]
