# Generated by Django 5.2.8 on 2026-02-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cartitem_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='provider_auth_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='service_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
