# Generated by Django 5.2.7 on 2025-11-26 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_provider', '0007_remove_localproviderpermission_service_pro_auth_us_cab487_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
        ),
    ]
