# Generated by Django 5.2.8 on 2026-01-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_billing_unit',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('PER_SESSION', 'Per Session'), ('ONE_TIME', 'One Time')], default='PER_SESSION', max_length=20),
        ),
    ]
