# Generated by Django 5.2.8 on 2026-01-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_services', '0002_service_default_billing_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.CharField(default='General', max_length=50)),
            ],
        ),
    ]
