# Generated by Django 5.2.8 on 2025-12-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_services', '0002_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
