# Generated by Django 5.2.8 on 2026-01-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_services', '0003_capability'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='service',
            field=models.CharField(default='VETERINARY', max_length=50),
        ),
        migrations.AlterField(
            model_name='capability',
            name='group',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='capability',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
