# Generated by Django 5.2.8 on 2026-01-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_services', '0004_capability_service_alter_capability_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='target_audience',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization'), ('BOTH', 'Both')], default='BOTH', max_length=20),
        ),
    ]
