# Generated by Django 5.2.8 on 2026-02-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_services', '0005_service_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='linked_capability',
            field=models.CharField(blank=True, help_text='Technical capability key for dynamic permissions (e.g. GROOMING, DAYCARE)', max_length=100, null=True),
        ),
    ]
