# Generated by Django 5.2.8 on 2026-02-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_services', '0006_service_linked_capability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='linked_capability',
            field=models.CharField(blank=True, help_text='Technical capability key for dynamic permissions (e.g. GROOMING, DAYCARE)', max_length=100, null=True, unique=True),
        ),
    ]
