# Generated by Django 5.2.8 on 2026-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_services', '0007_add_unique_to_linked_capability'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='daily_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_value',
            field=models.IntegerField(blank=True, help_text='Default minutes, hours, or session count', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='monthly_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_model',
            field=models.CharField(choices=[('FIXED', 'Fixed Total'), ('PER_UNIT', 'Per Unit (Min/Hr/Day)'), ('WEEKLY', 'Weekly Rate'), ('MONTHLY', 'Monthly Rate'), ('YEARLY', 'Yearly Rate')], default='PER_UNIT', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='service_duration_type',
            field=models.CharField(choices=[('MINUTES', 'Minutes (Slots)'), ('HOURS', 'Hours'), ('DAYS', 'Days (Date Range)'), ('SESSIONS', 'Sessions (Packages)'), ('DOCTOR_VISIT', 'Doctor Visit'), ('PRODUCT', 'Product (Quantity Only)'), ('SUBSCRIPTION', 'Subscription')], default='MINUTES', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='default_billing_unit',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('PER_SESSION', 'Per Session'), ('ONE_TIME', 'One Time')], default='PER_SESSION', max_length=20),
        ),
    ]
