# Generated by Django 5.2.8 on 2026-02-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_services', '0008_service_daily_capacity_service_duration_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='daily_capacity',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration_value',
        ),
        migrations.RemoveField(
            model_name='service',
            name='monthly_limit',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pricing_model',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_duration_type',
        ),
    ]
