# Generated by Django 5.2.7 on 2025-11-26 12:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('individual', 'Individual Provider'), ('organization', 'Organization Provider'), ('employee', 'Organization Employee')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('textarea', 'Textarea'), ('dropdown', 'Dropdown'), ('multiselect', 'Multiselect'), ('file', 'File Upload'), ('date', 'Date')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target', 'order', 'name'],
            },
        ),
    ]
