# Generated by Django 5.2.7 on 2025-11-29 06:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDocumentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('individual', 'Individual Provider'), ('organization', 'Organization Provider'), ('employee', 'Organization Employee')], max_length=20)),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('allowed_types', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target', 'order', 'label'],
            },
        ),
    ]
