# Generated by Django 5.2.8 on 2025-12-03 11:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0002_providerdocumentdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDocumentVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.UUIDField()),
                ('document_id', models.UUIDField()),
                ('file_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('filename', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
