# Generated by Django 5.2.8 on 2025-12-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0003_providerdocumentverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerdocumentverification',
            old_name='provider_id',
            new_name='auth_user_id',
        ),
    ]
