# Generated by Django 6.0 on 2026-03-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0005_add_definition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerdocumentdefinition',
            name='target',
            field=models.CharField(choices=[('individual', 'Individual Provider'), ('organization', 'Organization Provider'), ('employee', 'Organization Employee'), ('superadmin', 'Super Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='providerfielddefinition',
            name='target',
            field=models.CharField(choices=[('individual', 'Individual Provider'), ('organization', 'Organization Provider'), ('employee', 'Organization Employee'), ('superadmin', 'Super Admin')], max_length=20),
        ),
    ]
