# Generated by Django 5.2.8 on 2025-12-09 12:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_provider', '0009_remove_businessdetails_service_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('checked_out', 'Checked Out'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='service_provider.verifieduser')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.UUIDField()),
                ('plan_title', models.CharField(max_length=255)),
                ('plan_role', models.CharField(max_length=20)),
                ('billing_cycle_id', models.IntegerField()),
                ('billing_cycle_name', models.CharField(max_length=100)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='INR', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='provider_cart.providercart')),
            ],
            options={
                'unique_together': {('cart', 'plan_id', 'billing_cycle_id')},
            },
        ),
    ]
