# Generated by Django 5.2.8 on 2025-12-10 11:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_cart', '0001_initial'),
        ('service_provider', '0009_remove_businessdetails_service_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.UUIDField()),
                ('plan_title', models.CharField(max_length=255)),
                ('billing_cycle_id', models.IntegerField()),
                ('billing_cycle_name', models.CharField(max_length=100)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='INR', max_length=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_plans', to='service_provider.verifieduser')),
            ],
        ),
    ]
