# Generated by Django 5.2.8 on 2026-03-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_cart', '0002_purchasedplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedplan',
            name='checkout_session_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='purchasedplan',
            name='payment_gateway',
            field=models.CharField(default='STRIPE', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasedplan',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
