# Generated by Django 5.2.8 on 2026-04-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_cart', '0003_purchasedplan_checkout_session_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedplan',
            name='sync_entitlement_source',
            field=models.CharField(default='BILLING', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasedplan',
            name='sync_is_legacy_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasedplan',
            name='sync_metadata_json',
            field=models.JSONField(default=dict),
        ),
    ]
