# Generated by Django 5.2.8 on 2026-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
