# Generated by Django 5.2.8 on 2025-12-23 07:22

import django.db.models.deletion
import provider_dynamic_fields.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_provider', '0019_delete_providersyncedplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDocumentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('individual', 'Individual Provider'), ('organization', 'Organization Provider'), ('employee', 'Organization Employee')], max_length=20)),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('allowed_types', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('individual', 'Individual Provider'), ('organization', 'Organization Provider'), ('employee', 'Organization Employee')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('textarea', 'Textarea'), ('dropdown', 'Dropdown'), ('multiselect', 'Multiselect'), ('file', 'File Upload'), ('date', 'Date')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderTemplateCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('super_admin_category_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTemplateService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('super_admin_service_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='tabler-box', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_categories', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('definition_id', models.UUIDField()),
                ('file', models.FileField(upload_to=provider_dynamic_fields.models.provider_doc_upload_path)),
                ('filename', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=128, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_documents', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='provider_dynamic_fields.providercategory')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_facilities', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProviderPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(help_text='e.g. per_hour, per_day, fixed', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='provider_dynamic_fields.providerfacility')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_pricing', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderTemplateFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('super_admin_facility_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='provider_dynamic_fields.providertemplatecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTemplatePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('super_admin_pricing_id', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='provider_dynamic_fields.providertemplatecategory')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='provider_dynamic_fields.providertemplatefacility')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='provider_dynamic_fields.providertemplateservice')),
            ],
        ),
        migrations.AddField(
            model_name='providertemplatecategory',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='provider_dynamic_fields.providertemplateservice'),
        ),
        migrations.CreateModel(
            name='ProviderCapabilityAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_id', models.CharField(max_length=255)),
                ('service_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_id', models.CharField(blank=True, max_length=255, null=True)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
            options={
                'unique_together': {('user', 'plan_id', 'service_id', 'category_id', 'facility_id')},
            },
        ),
        migrations.CreateModel(
            name='ProviderFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_id', models.UUIDField()),
                ('value', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=provider_dynamic_fields.models.provider_profile_field_upload_path)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_field_values', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
            options={
                'unique_together': {('verified_user', 'field_id')},
            },
        ),
    ]
