# Generated by Django 5.2.7 on 2025-11-27 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_provider', '0008_delete_localproviderpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFieldDefinition',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('individual', 'Individual Provider'), ('organization', 'Organization Provider'), ('employee', 'Organization Employee')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('textarea', 'Textarea'), ('dropdown', 'Dropdown'), ('multiselect', 'Multiselect'), ('file', 'File Upload'), ('date', 'Date')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_id', models.UUIDField()),
                ('value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_field_values', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
            options={
                'unique_together': {('verified_user', 'field_id')},
            },
        ),
    ]
