# Generated by Django 5.2.8 on 2025-12-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0001_initial'),
        ('service_provider', '0021_organizationemployee_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providercapabilityaccess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='providercapabilityaccess',
            name='pricing_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='providercapabilityaccess',
            unique_together={('user', 'plan_id', 'service_id', 'category_id', 'facility_id', 'pricing_id')},
        ),
    ]
