# Generated by Django 5.2.7 on 2025-11-29 10:17

import django.db.models.deletion
import provider_dynamic_fields.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0001_initial'),
        ('service_provider', '0008_delete_localproviderpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDocumentDefinition',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('individual', 'Individual Provider'), ('organization', 'Organization Provider'), ('employee', 'Organization Employee')], max_length=20)),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('allowed_types', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target', 'order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='providerfieldvalue',
            name='verified_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_field_values', to='service_provider.verifieduser', to_field='auth_user_id'),
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('definition_id', models.UUIDField()),
                ('file', models.FileField(upload_to=provider_dynamic_fields.models.provider_doc_upload_path)),
                ('filename', models.CharField(max_length=512)),
                ('content_type', models.CharField(blank=True, max_length=128, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_documents', to='service_provider.verifieduser', to_field='auth_user_id')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
