# Generated by Django 5.2.8 on 2026-01-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0002_alter_providercapabilityaccess_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providertemplatecategory',
            name='linked_capability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
