# Generated by Django 5.2.7 on 2025-12-01 07:55

import provider_dynamic_fields.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0002_localdocumentdefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerfieldvalue',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=provider_dynamic_fields.models.provider_profile_field_upload_path),
        ),
        migrations.AlterField(
            model_name='localdocumentdefinition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localfielddefinition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
