# Generated by Django 5.2.8 on 2026-01-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0003_providertemplatecategory_linked_capability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providertemplatepricing',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
