# Generated by Django 5.2.8 on 2025-12-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0003_providerfieldvalue_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localdocumentdefinition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='providerdocument',
            options={},
        ),
        migrations.RemoveField(
            model_name='localdocumentdefinition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='localdocumentdefinition',
            name='updated_at',
        ),
    ]
