# Generated by Django 5.2.8 on 2026-01-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0004_alter_providertemplatepricing_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providertemplatepricing',
            name='duration',
            field=models.CharField(default='fixed', max_length=50),
        ),
        migrations.AlterField(
            model_name='providertemplatepricing',
            name='facility',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='provider_dynamic_fields.providertemplatefacility'),
        ),
    ]
