# Generated by Django 5.2.8 on 2026-02-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0005_alter_providertemplatepricing_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerpricing',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='providertemplatepricing',
            name='duration',
        ),
        migrations.AddField(
            model_name='providerpricing',
            name='billing_unit',
            field=models.CharField(default='PER_SESSION', help_text='HOURLY, DAILY, WEEKLY, PER_SESSION, ONE_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='providerpricing',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration for HOURLY/PER_SESSION billing', null=True),
        ),
        migrations.AddField(
            model_name='providertemplatepricing',
            name='billing_unit',
            field=models.CharField(default='PER_SESSION', help_text='HOURLY, DAILY, WEEKLY, PER_SESSION, ONE_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='providertemplatepricing',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration for HOURLY/PER_SESSION billing', null=True),
        ),
    ]
