# Generated by Django 5.2.8 on 2026-02-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0006_remove_providerpricing_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
