# Generated by Django 5.2.8 on 2026-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0007_providercategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='providertemplatecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
