# Generated by Django 5.2.8 on 2026-02-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0008_providertemplatecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='providertemplatefacility',
            name='default_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='providertemplatefacility',
            name='is_addon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providertemplatefacility',
            name='parent_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='provider_dynamic_fields.providertemplatefacility'),
        ),
    ]
