# Generated by Django 5.2.8 on 2026-02-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0009_providertemplatefacility_default_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providertemplatefacility',
            name='required_capability',
            field=models.CharField(blank=True, help_text='The capability key required to perform this facility (e.g., VETERINARY_DOCTOR)', max_length=100, null=True),
        ),
    ]
