# Generated by Django 5.2.8 on 2026-02-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0010_providertemplatefacility_required_capability'),
    ]

    operations = [
        migrations.AddField(
            model_name='providertemplatefacility',
            name='default_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Default duration for this service in minutes'),
        ),
    ]
