# Generated by Django 5.2.8 on 2026-02-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0011_providertemplatefacility_default_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpricing',
            name='daily_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerpricing',
            name='duration_value',
            field=models.IntegerField(blank=True, help_text='Value for non-minute durations (e.g. 10 sessions)', null=True),
        ),
        migrations.AddField(
            model_name='providerpricing',
            name='monthly_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerpricing',
            name='pricing_model',
            field=models.CharField(default='PER_UNIT', help_text='FIXED, PER_UNIT, DAILY, WEEKLY, MONTHLY, YEARLY', max_length=50),
        ),
        migrations.AddField(
            model_name='providerpricing',
            name='service_duration_type',
            field=models.CharField(default='MINUTES', help_text='MINUTES, HOURS, DAYS, SESSIONS, PRODUCT', max_length=50),
        ),
        migrations.AddField(
            model_name='providertemplatepricing',
            name='daily_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providertemplatepricing',
            name='duration_value',
            field=models.IntegerField(blank=True, help_text='Value for non-minute durations (e.g. 10 sessions)', null=True),
        ),
        migrations.AddField(
            model_name='providertemplatepricing',
            name='monthly_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providertemplatepricing',
            name='pricing_model',
            field=models.CharField(default='PER_UNIT', help_text='FIXED, PER_UNIT, DAILY, WEEKLY, MONTHLY, YEARLY', max_length=50),
        ),
        migrations.AddField(
            model_name='providertemplatepricing',
            name='service_duration_type',
            field=models.CharField(default='MINUTES', help_text='MINUTES, HOURS, DAYS, SESSIONS, PRODUCT', max_length=50),
        ),
    ]
