# Generated by Django 5.2.8 on 2026-02-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0012_providerpricing_daily_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerfacility',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='providerfacility',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='providerfacility',
            name='pricing_strategy',
            field=models.CharField(default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='providerfacility',
            name='protocol_type',
            field=models.CharField(default='MINUTES_BASED', max_length=20),
        ),
        migrations.AddField(
            model_name='providertemplatefacility',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='providertemplatefacility',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='providertemplatefacility',
            name='pricing_strategy',
            field=models.CharField(default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='providertemplatefacility',
            name='protocol_type',
            field=models.CharField(default='MINUTES_BASED', max_length=20),
        ),
    ]
