# Generated by Django 6.0 on 2026-02-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0013_providerfacility_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerfacility',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='facility_images/'),
        ),
        migrations.AddField(
            model_name='providertemplatefacility',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='template_facility_images/'),
        ),
    ]
