# Generated by Django 6.0 on 2026-02-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0014_providerfacility_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='facility_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='provider_dynamic_fields.providerfacility')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderTemplateFacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='template_facility_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='provider_dynamic_fields.providertemplatefacility')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
