# Generated by Django 6.0 on 2026-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0015_providerfacilityimage_providertemplatefacilityimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerfacility',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Buffer time after the service in minutes'),
        ),
        migrations.AddField(
            model_name='providerfacility',
            name='slot_granularity',
            field=models.PositiveIntegerField(default=15, help_text='Minimum interval between slots in minutes'),
        ),
        migrations.AddField(
            model_name='providertemplatefacility',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Buffer time after the service in minutes'),
        ),
        migrations.AddField(
            model_name='providertemplatefacility',
            name='slot_granularity',
            field=models.PositiveIntegerField(default=15, help_text='Minimum interval between slots in minutes'),
        ),
    ]
