# Generated by Django 5.2.8 on 2026-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0016_providerfacility_buffer_minutes_and_more'),
        ('service_provider', '0051_add_display_name_to_template_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='providertemplatecategory',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='providertemplatecategory',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='providertemplatecategory',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='providertemplatecategory',
            name='execution_mode',
            field=models.CharField(choices=[('SEQUENTIAL', 'Sequential (One after another)'), ('PARALLEL', 'Parallel (Concurrent execution)')], default='SEQUENTIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='providertemplatecategory',
            name='required_resources',
            field=models.ManyToManyField(blank=True, related_name='category_templates', to='service_provider.providerresource'),
        ),
    ]
