# Generated by Django 5.2.8 on 2026-03-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0017_add_display_name_to_template_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providertemplatecategory',
            name='linked_capability',
        ),
        migrations.AddField(
            model_name='providertemplatecategory',
            name='category_key',
            field=models.CharField(blank=True, help_text='Core immutable key defining access namespace.', max_length=100, null=True),
        ),
    ]
