# Generated by Django 5.2.8 on 2026-03-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_dynamic_fields', '0018_remove_providertemplatecategory_linked_capability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providertemplatecategory',
            name='category_key',
            field=models.CharField(db_index=True, default='TEMP', help_text='Core immutable key defining access namespace.', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
