# Generated by Django 5.2.8 on 2026-01-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='linked_capability',
            field=models.CharField(blank=True, help_text='Maps to a hardcoded capability e.g. VETERINARY_VITALS', max_length=100, null=True),
        ),
    ]
