# Generated by Django 5.2.8 on 2026-02-26 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_categories', '0003_category_is_system'),
        ('dynamic_services', '0009_remove_service_daily_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. appointment.create', max_length=100, unique=True)),
                ('module', models.CharField(help_text='e.g. appointments, consultation, lab', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='dynamic_services.service')),
            ],
        ),
    ]
