# Generated by Django 5.2.8 on 2026-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_categories', '0004_capability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='linked_capability',
        ),
        migrations.AddField(
            model_name='category',
            name='category_key',
            field=models.CharField(blank=True, help_text='Unique immutable key, e.g. BOARDING_BASIC', max_length=100, null=True),
        ),
    ]
