# Generated by Django 5.2.8 on 2026-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_categories', '0005_remove_category_linked_capability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_key',
            field=models.CharField(db_index=True, default='TEMP', help_text='Unique immutable key, e.g. BOARDING_BASIC', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
