# Generated by Django 6.0.2 on 2026-02-12 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_remove_petownerprofile_address_and_more'),
        ('pets', '0004_remove_petmedicalprofile_vaccination_records_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.UUIDField(help_text='UUID of the service provider')),
                ('service_id', models.UUIDField(help_text='UUID of the selected service')),
                ('facility_id', models.UUIDField(help_text='UUID of the selected facility')),
                ('selected_time', models.DateTimeField()),
                ('address_snapshot', models.JSONField(help_text='Snapshot of the address at time of booking')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customers.petownerprofile')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by', models.UUIDField(help_text='UUID of the user who performed the action')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
            ],
            options={
                'verbose_name_plural': 'Booking Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
