# Generated by Django 6.0.2 on 2026-02-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0002_remove_petownerprofile_address_and_more'),
        ('pets', '0004_remove_petmedicalprofile_vaccination_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_employee_id',
            field=models.UUIDField(blank=True, help_text='UUID of the assigned employee (for organizations)', null=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_employee_id__isnull', True), ('status__in', ['PENDING', 'CONFIRMED'])), fields=('provider_id', 'selected_time'), name='unique_provider_slot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_employee_id__isnull', False), ('status__in', ['PENDING', 'CONFIRMED'])), fields=('assigned_employee_id', 'selected_time'), name='unique_employee_slot'),
        ),
    ]
