# Generated by Django 6.0.2 on 2026-02-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_assigned_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of Service, Category, and Facility names', null=True),
        ),
    ]
