# Generated by Django 6.0.2 on 2026-02-19 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_service_snapshot'),
        ('pets', '0004_remove_petmedicalprofile_vaccination_records_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.UUIDField(help_text='UUID of the service provider')),
                ('assigned_employee_id', models.UUIDField(blank=True, help_text='UUID of the assigned employee', null=True)),
                ('service_id', models.UUIDField()),
                ('facility_id', models.UUIDField()),
                ('selected_time', models.DateTimeField()),
                ('service_snapshot', models.JSONField(blank=True, help_text='Snapshot of Service/Category/Facility names', null=True)),
                ('price_snapshot', models.JSONField(blank=True, help_text='Snapshot of pricing and billing units', null=True)),
                ('addons_snapshot', models.JSONField(blank=True, default=list, help_text='List of selected add-ons')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['selected_time'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_provider_slot',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_employee_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of the address at time of booking', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='booking_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.bookingitem'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='assigned_employee_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='facility_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='selected_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_snapshot',
        ),
    ]
