# Generated by Django 6.0.2 on 2026-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingitem_remove_booking_unique_provider_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='completion_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
