# Generated by Django 6.0.2 on 2026-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingitem_completed_at_bookingitem_completion_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='End time for range-based bookings (e.g. Boarding)', null=True),
        ),
    ]
