# Generated by Django 6.0.2 on 2026-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingitem_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='assigned_employee_id',
            field=models.CharField(blank=True, help_text='ID of the assigned employee', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='facility_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='service_id',
            field=models.CharField(max_length=255),
        ),
    ]
