# Generated by Django 5.2.8 on 2026-02-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_bookingitem_assigned_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='provider_auth_id',
            field=models.CharField(blank=True, help_text='Auth ID of the organization/clinic', max_length=255, null=True),
        ),
    ]
