# Generated by Django 6.0.2 on 2026-03-06 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingitem_provider_auth_id'),
        ('customers', '0002_remove_petownerprofile_address_and_more'),
        ('pets', '0005_alter_pet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkout_session_url',
            field=models.URLField(blank=True, help_text='Stripe hosted checkout URL', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_gateway',
            field=models.CharField(default='STRIPE', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Stripe checkout session ID or Payment Intent ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='VisitGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True, help_text='The clinic or provider where this visit takes place')),
                ('idempotency_key', models.UUIDField(blank=True, help_text='To prevent duplicate bookings on retries', null=True, unique=True)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_groups', to='customers.petownerprofile')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_groups', to='pets.pet')),
            ],
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='visit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='bookings.visitgroup'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['provider_id', 'selected_time', 'end_time'], name='bookings_bo_provide_e0dfdf_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['assigned_employee_id', 'selected_time'], name='bookings_bo_assigne_1f3652_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['pet', 'selected_time', 'end_time'], name='bookings_bo_pet_id_31b39a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['visit_group'], name='bookings_bo_visit_g_50814e_idx'),
        ),
        migrations.AddIndex(
            model_name='visitgroup',
            index=models.Index(fields=['organization_id', 'status'], name='bookings_vi_organiz_33b840_idx'),
        ),
        migrations.AddIndex(
            model_name='visitgroup',
            index=models.Index(fields=['idempotency_key'], name='bookings_vi_idempot_db5e08_idx'),
        ),
    ]
