# Generated by Django 6.0.2 on 2026-04-18 10:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_checkout_session_url_booking_payment_gateway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Invoice Sequence',
                'verbose_name_plural': 'Invoice Sequences',
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g. GST_STANDARD, VAT_EUROPE', max_length=50, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage rate (e.g. 18.00)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], default='ISSUED', max_length=20)),
                ('provider_snapshot', models.JSONField(help_text='Snapshot: name, address, tax_id, etc.')),
                ('customer_snapshot', models.JSONField(help_text='Snapshot: name, email, address, etc.')),
                ('tax_snapshot', models.JSONField(help_text='Snapshot: tax_mode, rates applied, etc.')),
                ('items_snapshot', models.JSONField(help_text='List of services, pets, and prices covered by this invoice')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/%d/')),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='bookings.booking')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='bookings_in_invoice_b2d0b9_idx'), models.Index(fields=['status'], name='bookings_in_status_13eeba_idx'), models.Index(fields=['issued_at'], name='bookings_in_issued__186555_idx')],
            },
        ),
    ]
