# Generated by Django 5.2.8 on 2025-12-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
