# Generated by Django 5.2.8 on 2025-12-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='user',
            name='pin_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
