# Generated by Django 5.2.8 on 2025-12-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_organization_id_user_pin_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
