# Generated by Django 5.2.8 on 2025-12-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='PENDING', max_length=20),
        ),
    ]
