# Generated by Django 5.2.8 on 2026-02-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_organization_id_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_length',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
