# Generated by Django 6.0 on 2026-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_permission_capability_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='capability_key',
            field=models.CharField(default='system.default', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='service_name',
            field=models.CharField(default='system', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='New Role', max_length=50),
        ),
    ]
