# Generated by Django 6.0 on 2026-03-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_permission_capability_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinic_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
